### ISSUE TITLE
Releases on github

### ISSUE THREAD

**Issue by Josephc3** [mbedmicro/DAPLink#118]
Would i be possible for a version of the current builds/releases to be included on the Github repo?, perhaps as a sub folder or as an external hosted link?

I have the issue that i do not have a full version of the keil MDK so cannot build the required interface firmware but it would be useful to be able to access them all up to date and in one place 

thanks,

Joe

**Comment by jupe** [comment]
Release versions is there already as binary, is it enough for you:
https://github.com/mbedmicro/DAPLink/releases/tag/v0241

**Comment by Josephc3** [comment]
Wow - learnt something new about github, did not know the "releases" tab existed, this is perfect! 
Exactly what i was looking for!
thanks!
