### ISSUE TITLE
Settings, and where to declare them

### ISSUE THREAD

**Issue by stevew817** [mbedmicro/DAPLink#13]
I see the latest commit to master pulls out the drive name, html file name and redirect link to a target-specific file in overrides. I assume the idea here is to separate target MCU from target board? If so, then the board ID and version ID should also move from app_config into the override file.

**Comment by c1728p9** [comment]
You can now customize aspects of your board via the board.c file.

**Comment by c1728p9** [comment]
Closing this issue.  Feel free to re-open if you have further questions.
