### ISSUE TITLE
uVision project cannot build

### ISSUE THREAD

**Issue by RdaZhongyao** [mbedmicro/DAPLink#140]
Sorry, this issue is about `mbedmicro/FlashAlgo`, and has been moved to https://github.com/mbedmicro/FlashAlgo/issues/22

My env:
```plain
Python 2.7.12
progen 0.9.2
Keil MDK 5.17
ARM Compiler 5.06 update 1 (build 61)
```
As the README.md says, execute cmd:
```
$ progen generate -t uvision
```
then open project `projectfiles\uvision\lpc4088\lpc4088.uvproj`, try to build the target, log shows:
```
Build target 'lpc4088'
```
then MDK UV4.EXE collapses.

anything wrong?

**Comment by c1728p9** [comment]
Hi @RdaZhongyao, were you able to resolve this problem?

**Comment by RdaZhongyao** [comment]
have resolved, see https://github.com/mbedmicro/FlashAlgo/issues/22
