### ISSUE TITLE
Source of flash_blob

### ISSUE THREAD

**Issue by markus-becker-tridonic-com** [mbedmicro/DAPLink#171]
I am trying to get custom STM32F401/F091 platforms supported by DAPLink on SWDAP/dipdap.

I assume I could start from lpc11u35_arm_watch_stm32f411_if and modify it to our needs. Would the flash_blob from https://github.com/mbedmicro/DAPLink/blob/master/source/target/st/stm32f411/flash_blob.c work also for F401/F091? If not, how could one get adequate blobs for ST? They do not seem to come from https://github.com/mbedmicro/FlashAlgo.

@MarceloSalazar

**Comment by MarceloSalazar** [comment]
@c1728p9 could you have a look please?

**Comment by c1728p9** [comment]
Hi @markus-becker-tridonic-com, the stm32f411 likely will not work with the F401 or F091. To get support for these devices they will need to be added to the FlashAlgo repo you mentioned.

**Comment by markus-becker-tridonic-com** [comment]
OK, moving the issue to https://github.com/mbedmicro/FlashAlgo/issues/25

**Comment by GenericWorkName** [comment]
@markus-becker-tridonic-com Hey, I'm trying to compile a firmware for stm32f401 myself on the lpc11u35.
If you managed to compile one, I'd be really happy if you could send it to me.
