### ISSUE TITLE
Assert filenames missing from interface on Kinetis

### ISSUE THREAD

**Issue by c1728p9** [mbedmicro/DAPLink#200]
Assert filenames were unintentionally disabled for both the interface and bootloader in #151 . They should only be disabled for the K20 and KL26 bootloader to safe space. 

CC @flit

**Comment by flit** [comment]
@c1728p9 Oops, sorry, how did I screw it up?

**Comment by c1728p9** [comment]
I think it is because these files are common to both the bootloader and interface:
records/hic_hal/k20dx.yaml
records/hic_hal/kl26z.yaml

**Comment by flit** [comment]
What about splitting `DAPLINK_NO_ASSERT_FILENAMES` into `DAPLINK_NO_BL_ASSERT_FILENAMES` and `DAPLINK_NO_IF_ASSERT_FILENAMES`?

**Comment by flit** [comment]
@c1728p9 Any feedback on this?

**Comment by c1728p9** [comment]
Sorry, missed your comment. That sounds like a good solution.

**Comment by c1728p9** [comment]
I created #203 as a simple fix for this. Hopefully it will never get to the point where asserts need to be turned off on the interface.

**Comment by flit** [comment]
Ok, thanks. Sorry I didn't have a chance to get to it right away.
