### ISSUE TITLE
Add link to HDK from Readme

### ISSUE THREAD

**Issue by BlackstoneEngineering** [mbedmicro/DAPLink#233]
Need to add link to the HDK from the readme file to complete the circular linkage from the HDK page. 

Something like

## Hardware Reference Implementation
DAPLink Reference Designs can be found in the [mbed HDK DAPLink Reference Design](https://github.com/ARMmbed/mbed-HDK/tree/master/Production%20Design%20Projects/DAPLink) projects.

**Comment by c1728p9** [comment]
@BlackstoneEngineering Please re-open if this is something that should still be done. As is, the HDK link doesn't work.
