### ISSUE TITLE
Unable to generate APP

### ISSUE THREAD

**Issue by neomissing** [mbedmicro/DAPLink#254]
*** Using Compiler 'V5.06 update 4 (build 422)', folder: 'C:\Keil_v5\ARM\ARMCC\Bin'
Build target 'kl27z_frdmkl27z_if'
Before Build - User command #1: ..\..\..\tools\pre_build_script.bat
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>copy ..\..\..\source\daplink\version_git_tmpl.txt ..\..\..\source\daplink\version_git.h 
已复制         1 个文件。
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>python ..\..\..\tools\pre_build_script.py 
#> Pre-build script start
#> Old git version file removed
#> Getting git SHA
#> Checking for local changes
#> Creating new git version file
#> Pre-build script completed
compiling vfs_user.c...
compiling vfs_manager.c...
linking...
Program Size: Code=38908 RO-data=5360 RW-data=592 ZI-data=12572  
After Build - User command #1: ..\..\..\tools\post_build_script.bat C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if C:\Keil_v5\ARM
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>fromelf --bin C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.axf -o C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.bin 
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>fromelf --i32 C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.axf -o C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.hex 
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>python ..\..\..\tools\post_compute_crc.py C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.hex C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if_crc 
Traceback (most recent call last):
  File "..\..\..\tools\post_compute_crc.py", line 137, in <module>
    main()
  File "..\..\..\tools\post_compute_crc.py", line 58, in main
    new_hex_file.fromfile(input_file, format='hex')
  File "C:\Python27\lib\site-packages\intelhex\__init__.py", line 246, in loadfile
    self.loadhex(fobj)
  File "C:\Python27\lib\site-packages\intelhex\__init__.py", line 196, in loadhex
    fobj = open(fobj, "r")
IOError: [Errno 13] Permission denied: 'C:\\Users\\neomissing\\Desktop\\DAPLink\\projectfiles\\uvision\\kl27z_frdmkl27z_if\\build\\kl27z_frdmkl27z_if.hex'
".\build\kl27z_frdmkl27z_if.axf" - 1 Error(s), 0 Warning(s).
Target not created.
Build Time Elapsed:  00:00:04

I tried to transplant to MKL27Z256VFM4, boot is OK, but APP can not generate

**Comment by c1728p9** [comment]
Hi @neomissing, after the build was the file `C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.hex` created? If not that would explain why there was an IOError in the python script.

**Comment by neomissing** [comment]
kl27z_frdmkl27z_if.hex not created,What is the reason?Need to change what configuration。

**Comment by c1728p9** [comment]
Hi @neomissing, this command from your log above should be creating the .hex file:
```
C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if>fromelf --i32 C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.axf -o C:\Users\neomissing\Desktop\DAPLink\projectfiles\uvision\kl27z_frdmkl27z_if\build\kl27z_frdmkl27z_if.hex
```

You could try running this manually and see why it isn't creating `kl27z_frdmkl27z_if.hex `. I would also check to make sure you have `kl27z_frdmkl27z_if.axf` which should have been created by uvision.

**Comment by c1728p9** [comment]
Please re-open if you are having further problems with this.
