### ISSUE TITLE
How to change DAPLINK baud-rate at run time

### ISSUE THREAD

**Issue by akrnvm** [mbedmicro/DAPLink#260]
How DPALINK will work in different baud-rates ?

In my DAPLINK it fixed the baud-rate as 9600,hence its not able to prints different baud-rate applications messages(115200). how can I modify DAPLINK code to common for all baud-rates without changing in serial driver (for baud-rate )in each time.

DAPLINK with fixed boud-rate is expect behavior or shall i need to change my driver to handle all baud-rates dynamically ?

Please anyone can clarify

**Comment by flit** [comment]
Baud rate is specified via USB CDC.

**Comment by pranavshandilya** [comment]
[https://developer.mbed.org/questions/77827/Daplink-baud-rate-changing/](url)
@akrnvm The same question was actually posted to the developer site today.

I did the same thing in my DAPlink, 
In uart.c, under uart_initialize function Baud rate is fixed to 9600.

@flit Could you please elaborate this answer?

**Comment by c1728p9** [comment]
Hi @akrnvm and @pranavshandilya, the baudrate in uart_initialize doesn't matter, the host does not read data until it configures the UART (which sets the baudrate). This is done in the function [uart_set_configuration](https://github.com/mbedmicro/DAPLink/blob/master/source/hic_hal/uart.h#L81).

To change the baudrate you'll need to select a new baudrate in the terminal program you are using (programs like CoolTerm, Tera Term, PuTTY, Hyperterminal, screen, ...). More info can be found in the [serial communication docs](https://docs.mbed.com/docs/mbed-os-handbook/en/latest/getting_started/serial_communication/).

**Comment by pranavshandilya** [comment]
Hi, @c1728p9 Thanks

I'll try your suggestion, Once it is done I'll inform you.

**Comment by akrnvm** [comment]
RTS/CTS flow-control pins are required for this? in my target board only Tx pin and Rx pin are connected with DAPlink. 

in "uart_set_configuration" function i'm re-init my UART with config->baudrate, but its not reflect in my output.
 is this "config->baudrate" value is "9600" , "115200",etc values or some thing else?

**Comment by c1728p9** [comment]
Hi @akrnvm, what terminal program are you using on the PC to open the serial port?

**Comment by akrnvm** [comment]
@c1728p9 thank you for your support.
i'm using Tera-Term as terminal program in my PC.
Now the issue got resolved, it was a code mistake from my side.
