### ISSUE TITLE
DAPLink on custom board for Target LPC1768(Non Mbed enable board).

### ISSUE THREAD

**Issue by pranavshandilya** [mbedmicro/DAPLink#261]
A year ago, I have created bootloader and interface firmware for a custom controller(DAPLink V203) and it's working fine with Target controller LPC1768. I'm able to do Automated testing and everything.

But now same code ported to new DAPLink(V243) with reference of bootloader sam3u2c_bl and interface firmware sam3u2c_mkit_dk_dongle_nrf5x_if, and it's not working.

Individually it's working means when I download bootloader to controller "MAINTENANCE" drive is showing but after copying interface firmware into the drive, it disappears after restart nothing is happening.
But the same interface firmware is working with an old bootloader(V203).

ROM size: 128KB
RAM size: 48KB

Why it's not working with a combination of the new bootloader(V243)?
Please anyone can help me for this, Thanks..!

**Comment by c1728p9** [comment]
Hi @pranavshandilya, what offset does your bootloader to expect the application to start at? If this is out of sync with DAPLink then the image will not be bootable.

**Comment by pranavshandilya** [comment]
Hi, @c1728p9  Thanks for your valuable reply..!!
My bootloader expect offset 32KB(0x00008000) but I'm giving 0KB.
Thanks for your help after changing this address, it;s working fine,
Below is the code what I changed.

#include "target_config.h"
```
const char *board_id = "0000";

//  target information
target_cfg_t target_device = {
    .sector_size    = 0x1000,
    // Assume memory is regions are same size. Flash algo should ignore requests
    //  when variable sized sectors exist
    // .sector_cnt = ((.flash_end - .flash_start) / .sector_size);
    .sector_cnt     = (KB(128) / 0x1000),
    .flash_start    = KB(32),
    .flash_end      =KB(128),
    .ram_start      = 0x20000000,
    .ram_end        = 0x2000C000
    /* .flash_algo not needed for bootloader */
};
```
```
const char *board_id = "0000";

// atsam3u2c target information
target_cfg_t target_device = {
    .sector_size    = 0x1000,
    // Assume memory is regions are same size. Flash algo should ignore requests
    //  when variable sized sectors exist
    // .sector_cnt = ((.flash_end - .flash_start) / .sector_size);
    .sector_cnt     = (KB(128) / 0x1000),
    .flash_start    = KB(32),
    .flash_end      =KB(128),
    .ram_start      = 0x20000000,
    .ram_end        = 0x2000C000
    /* .flash_algo not needed for bootloader */
};
```

**Comment by c1728p9** [comment]
I'm glad I could help :smile:
