### ISSUE TITLE
DAPlink remove boot, app at least how much flash and ram

### ISSUE THREAD

**Issue by neomissing** [mbedmicro/DAPLink#276]
I would like to transplant to the new MCU above, would like to know how much flash and ram DAPlink need？

**Comment by c1728p9** [comment]
For all new interfaces I would recommend 256KB rom and 32KB ram. Otherwise you may run out of space as new features are added.

**Comment by c1728p9** [comment]
Closing this issue. Please re-open if you have further questions.
