### ISSUE TITLE
Can I develop a flash burning tool based on CMSIS_DAP.dll?

### ISSUE THREAD

**Issue by wayen30** [mbedmicro/DAPLink#279]
I use the keil/daplink to write firmware to flash. 
 I want to develop a flash burning tool . I think devleop based on CMSIS_DAP.dll is a good idea. 
But I did not find information about CMSIS_DAP.dll. Can someone provide it? Thank you!

**Comment by c1728p9** [comment]
I don't know info on CMSIS_DAP.dll offhand. A possible alternative you might consider is using pyOCD flashtool. Its free and open source and you can use it to flash boards.

**Comment by wayen30** [comment]
ok. I will try pyOCD.Thanks!
