### ISSUE TITLE
DAPLink boot for K20  and app for KL26 not work

### ISSUE THREAD

**Issue by neomissing** [mbedmicro/DAPLink#281]
I try to compile DAPLink BOOT, found that the firmware can not work after programming, compile CMSIS DAP BOOT, can work properly, DAPLink APP does not work

**Comment by c1728p9** [comment]
Hi @neomissing, what APP firmware are you trying to use and for what board? Some versions of the CMSIS-DAP bootloader have an application offset of 0x5000, while all versions of the DAPLink bootloader have an application offset of 0x8000.

**Comment by neomissing** [comment]
I compiled DAPLink K20 boot, but no response to the K20 programming, I found that many people have this problem, I try to compile CMSIS DAP K20 boot, programmed to K20 can work, I also compiled the same programming DAPLink APP, found It is not working

**Comment by c1728p9** [comment]
@neomissing can you attach both bootloader and the application you are loading so I can take a look?

**Comment by c1728p9** [comment]
Please re-open this issue if you have more information or need additional help.
