### ISSUE TITLE
The latest LPC11U35 firmware update failed

### ISSUE THREAD

**Issue by neomissing** [mbedmicro/DAPLink#322]
Compile the latest source code, generate LPC11U35 firmware and found a direct U disk update firmware will fail, the previous firmware no problem, but the latest firmware can be used to burn the simulator can work, where changes lead to this problem?

**Comment by c1728p9** [comment]
Hi @neomissing, what do you mean by U disk update? What file are you loading? Is the device in CRP disabled mode?

**Comment by neomissing** [comment]
lpc11u35_lpc824xpresso_if,the device in CRP disabled mode,update LPC11U35 firmware,

**Comment by c1728p9** [comment]
Try using lpc11u35_lpc824xpresso_if_crc.bin instead. CRP disabled mode requires the CRCed version of the binary.

**Comment by neomissing** [comment]
Thanks,I try lpc11u35_lpc824xpresso_if_crc.bin ,it's OK.

**Comment by c1728p9** [comment]
Good to hear. Can this issue be closed?
